### ISSUE TITLE
[v1.0.0] - Infinite loop on join call

### ISSUE THREAD

**Issue by AlessandroFrangiamoneIriscube** [Azure/communication-ui-library-android#658] opened 2022-12-05 12:16 UTC
Hi,
We have a problem entering the calls.
We have set up push notifications via acsid and azure token.
By carrying out a test using your tool (https://github.com/Azure-Samples/communication-services-web-calling-tutorial) we are able to receive notifications with the call ID.
Using this call ID within the CallCompositeGroupCallLocator as indicated in your guide ( https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/ui-library/get-started-composites?tabs=kotlin&pivots=platform-android ), specifically with the code:

`CallCompositeGroupCallLocator(UUID.fromString("GROUP_CALL_ID"))`

The first settings screen opens, however pressing the "Join Call" button activates the loader on the button but continues to load endlessly into the application. Even the above mentioned tool remains in the "ringing" state.
Here an example of what is displayed in the app and in the tool:
<img width="205" alt="Screenshot 2022-12-05 at 13 12 02" src="https://user-images.githubusercontent.com/92713518/205634473-2b71cd6f-a15d-40fa-ac22-ee5312e42cb5.png">
<img width="500" alt="Screenshot 2022-12-05 at 13 10 29" src="https://user-images.githubusercontent.com/92713518/205634517-34c6d699-a161-4d17-8209-cb4425d7f931.png">

Could you give us support?

Thank you,
Alessandro

**Comment by PAMAZ** [comment] 2022-12-12 17:47
Hi,

we tried to run our call and we got this exception:

2022-12-12 18:45:48.818 27250-8912/com.mediolanum.android.fullbanca I/communication.ui: com.azure.android.communication.ui.calling.redux.action.CallingAction$CallStartRequested@62f2fb6
2022-12-12 18:45:48.845 4227-4525/? I/Pageboost: Launcher App Execution
2022-12-12 18:45:48.859 27250-8938/com.mediolanum.android.fullbanca W/System.err: java.util.concurrent.ExecutionException: com.azure.android.communication.calling.CallingCommunicationException: Multiple CallAgent with the same identity is not allowed
2022-12-12 18:45:48.859 27250-8938/com.mediolanum.android.fullbanca W/System.err:     at java9.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:399)
2022-12-12 18:45:48.860 27250-8938/com.mediolanum.android.fullbanca W/System.err:     at java9.util.concurrent.CompletableFuture.get(CompletableFuture.java:2079)
2022-12-12 18:45:48.860 27250-8938/com.mediolanum.android.fullbanca W/System.err:     at com.azure.android.communication.calling.CallClient$3.get(CallClient.java:203)
2022-12-12 18:45:48.860 27250-8938/com.mediolanum.android.fullbanca W/System.err:     at com.azure.android.communication.calling.CallClient$3.get(CallClient.java:181)
2022-12-12 18:45:48.860 27250-8938/com.mediolanum.android.fullbanca W/System.err:     at java9.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1774)
2022-12-12 18:45:48.860 27250-8938/com.mediolanum.android.fullbanca W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2022-12-12 18:45:48.861 27250-8938/com.mediolanum.android.fullbanca W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2022-12-12 18:45:48.861 27250-8938/com.mediolanum.android.fullbanca W/System.err:     at java.lang.Thread.run(Thread.java:923)
2022-12-12 18:45:48.861 27250-8938/com.mediolanum.android.fullbanca W/System.err: Caused by: com.azure.android.communication.calling.CallingCommunicationException: Multiple CallAgent with the same identity is not allowed
2022-12-12 18:45:48.861 27250-8938/com.mediolanum.android.fullbanca W/System.err:     at com.azure.android.communication.calling.NativeLibraryHelpers.checkStatus(NativeLibraryHelpers.java:179)
2022-12-12 18:45:48.862 27250-8938/com.mediolanum.android.fullbanca W/System.err:     at com.azure.android.communication.calling.CallClient$1.get(CallClient.java:120)
2022-12-12 18:45:48.862 27250-8938/com.mediolanum.android.fullbanca W/System.err:     at com.azure.android.communication.calling.CallClient$1.get(CallClient.java:113)

Could it be the reason of infinite joining?

Paolo

**Comment by iaulakh** [comment] 2022-12-13 03:11
Hi @PAMAZ, @AlessandroFrangiamoneIriscube,

Thank you for sharing the logs. would it be possible to know the version of UI library leveraged in your applications? 

Please let us know if you have modified code regarding call agent initialization. We can look at code to see the possible cause of error.

Thanks,
Inderpal

**Comment by PAMAZ** [comment] 2022-12-13 10:27
Hi @iaulakh,

these are the versions of the azure libraries used in our project:

- "com.azure.android:azure-communication-ui-calling:1.0.0"
- "com.azure.android:azure-communication-calling:1.2.0-beta1"

Below you can find our call initialization:

`callLink?.let { link ->
            azureManager.retrieveRefreshToken()?.let { token ->
                val communicationTokenRefreshOptions = CommunicationTokenRefreshOptions({ token }, true)
                CallCompositeBuilder()
                        .theme(R.style.AzureHybrid_CallComposite)
                        .localization(CallCompositeLocalizationOptions(CallCompositeSupportedLocale.IT_IT))
                        .build()
                        .launch(this,
                                CallCompositeRemoteOptions(
                                        CallCompositeGroupCallLocator(UUID.fromString(link)),
                                        CommunicationTokenCredential(communicationTokenRefreshOptions),
                                        Application.getPersistentDataManager(this).name ?: ""
                                )
                        )
            }
        }`

Thanks,
Paolo

**Comment by iaulakh** [comment] 2022-12-13 14:08
Hi @PAMAZ,

Thank you for sharing the code.

You do not need to include `com.azure.android:azure-communication-calling:1.2.0-beta1`.  `com.azure.android:azure-communication-ui-calling:1.0.0` will fetch required version of `com.azure.android:azure-communication-calling`. 

do you have any specific code that requires `com.azure.android:azure-communication-calling:1.2.0-beta1`?

Thanks,
Inderpal

**Comment by PAMAZ** [comment] 2022-12-13 14:20
Hi! 

I used previously the V1.0.0 ui library, I used the beta only for the Diagnostic tool integrated on it.

The error occurs even with the 1.0.0 version.

Thanks,
Paolo

**Comment by iaulakh** [comment] 2022-12-13 19:13
Hi @PAMAZ, 

would it be possible to have quick call to look at use case and issue reproduction. We are not able to reproduce issue. I am in PST timezone. Please share your convenient time.

Thanks,
Inderpal

**Comment by LorenzoBarrancos** [comment] 2022-12-16 15:45
Hi @iaulakh, 
are you available for a call on 19 December 2022 from 17:00 to 18:00 (Italian Rome timezone) ?

The same issue is on iOS can you please invite also an iOS support team member?

Let us know and if you can share me an email for the invitation. 

Thank you,
Lorenzo

**Comment by iaulakh** [comment] 2022-12-16 16:32
Sounds good @LorenzoBarrancos. please share your email address, I will send meeting invite.

**Comment by iaulakh** [comment] 2023-01-31 16:39
Closing issue as email conversations is in progress.

**Closed by iaulakh** 2023-01-31 16:39 UTC
