### ISSUE TITLE
Azure Communication Calling SDK crashes on start call in release mode 

### ISSUE THREAD

**Issue by AhmedKhattab95** [Azure/communication-ui-library-android#844] opened 2023-10-10 09:56 UTC
**Describe the bug**
Azure Communication Calling SDK crashes on start call when try it in release mode 

**To Reproduce**
start new Call 
with this code:
```
    public void startCallComposite(){
        CommunicationTokenRefreshOptions communicationTokenRefreshOptions =
                new CommunicationTokenRefreshOptions(this::fetchToken, true);
        CommunicationTokenCredential communicationTokenCredential =
                new CommunicationTokenCredential(communicationTokenRefreshOptions);
        CallCompositeJoinLocator locator = new CallCompositeTeamsMeetingLinkLocator(dataModel.meetingUrl);
        CallCompositeRemoteOptions remoteOptions = new CallCompositeRemoteOptions(
                locator,
                communicationTokenCredential,
                dataModel.userName);
        CallCompositeLocalizationOptions localOptions = new CallCompositeLocalizationOptions(new Locale("ar"));
        CallComposite call = new CallCompositeBuilder()
                .localization(localOptions)
                .theme(AppCompatDelegate.MODE_NIGHT_YES)
                .build();
        CallCompositeSetupScreenViewData screenViewData = new CallCompositeSetupScreenViewData();
        screenViewData.setTitle(dataModel.lawsuitsSessionName);
        CallCompositeLocalOptions callCompositeLocalOptions = new CallCompositeLocalOptions();
        callCompositeLocalOptions.setSetupScreenViewData(screenViewData);
        call.launch(context, remoteOptions, callCompositeLocalOptions);
        AzureCommunicationTelemetriesHandler.getInstance().subscribeEvents(call);
    }

```
will give this exception and cause the app to crash and here is exception from firebase crashlitics

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.moj.najiz/com.azure.android.communication.ui.calling.presentation.CallCompositeActivity}: z4.d: Configuration with instanceId:0 does not exist. Please ensure that you have set a valid instanceId before retrieving the container.
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4060)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4247)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8668)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
       
       Caused by z4.d: Configuration with instanceId:0 does not exist. Please ensure that you have set a valid instanceId before retrieving the container.
       at com.azure.android.communication.ui.calling.presentation.DependencyInjectionContainerHolder.setInstanceId(DependencyInjectionContainerHolder.java:40)
       at com.azure.android.communication.ui.calling.presentation.CallCompositeActivity.onCreate(CallCompositeActivity.java:8)
       at android.app.Activity.performCreate(Activity.java:8214)
       at android.app.Activity.performCreate(Activity.java:8202)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4033)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4247)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8668)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
       
       Caused by java.lang.IllegalArgumentException: Configuration with instanceId:0 does not exist. Please ensure that you have set a valid instanceId before retrieving the container.
       at com.azure.android.communication.ui.calling.presentation.DependencyInjectionContainerHolder.setInstanceId(DependencyInjectionContainerHolder.java:37)
       at com.azure.android.communication.ui.calling.presentation.CallCompositeActivity.onCreate(CallCompositeActivity.java:8)
       at android.app.Activity.performCreate(Activity.java:8214)
       at android.app.Activity.performCreate(Activity.java:8202)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4033)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4247)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8668)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
```
**Expected behavior**
work fine in release mode  as in debug mode

**AzureCommunicationUILibrary (please complete the following information):**
- [1.4.0 release](https://github.com/Azure/communication-ui-library-android/releases/tag/calling-v1.4.0)
 
**Smartphone (please complete the following information):**
 - Device: huawei nova 5t
 - API: [e.g. API29]

**Comment by ahammer** [comment] 2023-10-17 09:44
Hi Ahmed,

I am in the process of investigating the issue you reported. Based on the provided code, I have been able to reproduce the problem. The log files also indicate that there's an initialization failure.

To delve deeper and better understand the root cause, it would be beneficial if you could provide the ACS Logs. These logs often contain more detailed information that can aid in the troubleshooting process.

For guidance on how to enable and access these logs, please refer to the following Microsoft documentation: [ACSTroubleshooting - Accessing Logs](https://learn.microsoft.com/en-us/azure/communication-services/concepts/troubleshooting-info?tabs=csharp%2Candroid%2Cdotnet#enable-and-access-call-logs).

**Comment by AhmedKhattab95** [comment] 2023-10-17 10:12
@ahammer please try it in release mode not debug as it crash in release mode

**Comment by ahammer** [comment] 2023-10-17 22:01
Unfortunately, in release mode I am also not able to reproduce.

To effectively diagnose the issue you're encountering, I'd appreciate if you could provide the following details:

1. **LogCat Output:** The Android system logs will give insights into any errors or warnings around the time the issue occurred.

2. **ACS Logs:** If available, please pull the ACS logs directly from the device.

3. **Device Specificity:** Is this issue occurring on a specific device or model, or is it seen across multiple devices?

4. **Android OS Version:** Does the issue seem to be tied to a particular Android OS version?

5. **Issue Occurrence:** Is this error seen only in the release version of the app, or was it also encountered during the development phase? Is it regularly reproducible in a development environment?

6. **Screen Title Samples:** I lack the data related to "screen title". If you could provide samples, it would be immensely helpful.

7. **Additional Troubleshooting Information:** Please include any other relevant details or observations that might assist in resolving the problem.

**Issue Context/Analysis**

For clarity, the problem appears to originate from the following file: [CallCompositeInstanceManager.kt](https://github.com/Azure/communication-ui-library-android/blob/main/azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallCompositeInstanceManager.kt). Its primary function is to maintain information about the currently active Call Composite.

The registration of the `CallCompositeInstance` should occur upon launch. Specifically, the sequence is expected to be: launch -> launchComposite -> registration. The relevant code segment can be found [here](https://github.com/Azure/communication-ui-library-android/blob/b836e52073b4182c1246db0976069c8aad958e26/azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallComposite.java#L359).

From my initial understanding, potential causes for a crash during this process include:

1. **Configuration Discrepancies:** There might be differences between release and debug configurations. For instance, a possible missing implementation of the token function.

2. **Static Memory Issues:** The `CallCompositeInstanceManager` uses static memory to store its instances. If static memory isn't shared, either due to the application running in a different process or because Android terminated and then recreated the process, the instances will be lost. It's noteworthy that the underlying Native Calling SDK isn't designed to naturally recover from process terminations in the way Android does.

The static is used to facilitate inter-process communication of things like Token Functions that can't be serialized and sent by intent to the Call Composite activity, and a way to keep our Call State decoupled from the activity so we have flexibility in bindings.

Please ensure there are no developer settings that might affect the app's processes or its memory management.

**Comment by iaulakh** [comment] 2024-01-29 17:15
Hi @AhmedKhattab95,

Closing the issue due to lack of updates. Please reopen if necessary.

**Closed by iaulakh** 2024-01-29 17:15 UTC

**Comment by watermelon-mann** [comment] 2025-10-09 11:25
Hey @AhmedKhattab95 sorry for reviving this conversation but I'm encountering the same issue and this is the only resource I found. Have you been able to find out what was the problem? Did you solve it?

Thanks @ahammer, your response is very insightful, it would have been very helpful if you could answer the following questions too.
Is my understanding correct that the library uses native (C, C++) code internally? Does that mean that I have to add some pro-guard rules for obfuscation to avoid this problem?

**Comment by watermelon-mann** [comment] 2025-10-09 17:01
I'm getting a bit deeper in the rabbit hole, and in my case, it _might_ be because of dexguard, I suppose that's the reason why @ahammer was not able to replicate it, @AhmedKhattab95 did you have dexguard in your project, and @ahammer can you confirm that the crash indeed happens when you have dexguard in your project?

**Comment by watermelon-mann** [comment] 2025-10-13 09:35
just putting this here for anyone in the future, the problem in my case was DexGuard
the pro-guard rules form [this discussion](https://github.com/Azure/Communication/issues/69#issuecomment-713096637) helped me
